### ISSUE TITLE
Support readme.md in place of readme.txt

### ISSUE THREAD

**Issue by mauteri** [skaut/wordpress-version-checker#1193]
I'm working on a WordPress plugin project and we're looking to do away with readme.txt and use readme.md. This has been apparently supported since 2015.

https://johnblackbourn.com/readme-md-plugin-on-wordpress-org/

John also provided a sample here https://github.com/johnbillion/user-switching/blob/develop/readme.md

Currently wordpress-version-checker is failing since we removed the readme.txt

```
Error: Couldn't get the repository readme. Error message: No readme file was found in repo and all usual locations were exhausted.
```
Thx!

**Comment by mauteri** [comment]
I tried settings `.wordpress-version-checker.json` with
```
{
	"readme": "README.md"
}
```
just to see if that would work, but didn't.

**Comment by marekdedic** [comment]
Hi, thanks, I didn't know about markdown readmes, so the tool doesn't support them. Should be a pretty easy fix.

**Comment by marekdedic** [comment]
Ok, so I investigated a little bit and this is actually 2 issues at once:

1. `readme.md` is not in the default list this tool checks, even though wp.org accepts it (although I couldn't find any references to it apart from your blogpost and https://meta.trac.wordpress.org/ticket/403). Btw, you blog has an expired cert. I'll add it
2. Your readme contains whitespace at the end of the "Tested up to" line, causing it not to parse. I'll make the regexp more robust, but you probably should strip the whitespace anyway.

**Comment by marekdedic** [comment]
Closing in favor of:
-

**Comment by mauteri** [comment]
@marekdedic just tested, this works great (all my checks are passing now)! Also I noticed the cert was expired too, but isn't my blog :-D
