### ISSUE TITLE
Optional flag to check at Release Candidate phase

### ISSUE THREAD

**Issue by jeffpaul** [skaut/wordpress-version-checker#880]
When a major WordPress release hits the initial Release Candidate phase (aka RC1), that's generally a good time to start testing for compatibility and then bumping the "tested up to" value.  It would be nice to have an optional flag or something with the action here to not check against the latest WordPress version but perhaps the latest WordPress version OR one that's in development and at least at the RC1 phase.

**Comment by marekdedic** [comment]
Hi,
that's a good idea, however, do you know of any way to automatically find out when a new version hits the RC phase? Currently the code just checks https://api.wordpress.org/core/stable-check/1.0/, but I don't think a new version appears there until its released...

**Comment by jeffpaul** [comment]
@marekdedic I heard from @desrosj that while there's not an API specifically in core for this, we might be able to use `http://api.wordpress.org/core/version-check/1.7/` to grab the latest dev version offered by .org.  Example in Core https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/update.php#L173-L186

**Comment by marekdedic** [comment]
`https://api.wordpress.org/core/version-check/1.7/?channel=rc` as of today (an RC exists):
```json
{
   "offers":[
      {
         "response":"development",
         "download":"https:\/\/downloads.wordpress.org\/release\/wordpress-6.2-RC4.zip",
         "locale":"en_US",
         "packages":{
            "full":"https:\/\/downloads.wordpress.org\/release\/wordpress-6.2-RC4.zip",
            "no_content":false,
            "new_bundled":false,
            "partial":false,
            "rollback":false
         },
         "current":"6.2-RC4",
         "version":"6.2-RC4",
         "php_version":"5.6.20",
         "mysql_version":"5.0",
         "new_bundled":"6.1",
         "partial_version":false
      },
      {
         "response":"autoupdate",
         "download":"https:\/\/downloads.wordpress.org\/release\/wordpress-6.2-RC4.zip",
         "locale":"en_US",
         "packages":{
            "full":"https:\/\/downloads.wordpress.org\/release\/wordpress-6.2-RC4.zip",
            "no_content":false,
            "new_bundled":false,
            "partial":false,
            "rollback":false
         },
         "current":"6.2-RC4",
         "version":"6.2-RC4",
         "php_version":"5.6.20",
         "mysql_version":"5.0",
         "new_bundled":"6.1",
         "partial_version":false,
         "new_files":true
      },
      {
         "response":"latest",
         "download":"https:\/\/downloads.wordpress.org\/release\/wordpress-6.1.1.zip",
         "locale":"en_US",
         "packages":{
            "full":"https:\/\/downloads.wordpress.org\/release\/wordpress-6.1.1.zip",
            "no_content":"https:\/\/downloads.wordpress.org\/release\/wordpress-6.1.1-no-content.zip",
            "new_bundled":"https:\/\/downloads.wordpress.org\/release\/wordpress-6.1.1-new-bundled.zip",
            "partial":false,
            "rollback":false
         },
         "current":"6.1.1",
         "version":"6.1.1",
         "php_version":"5.6.20",
         "mysql_version":"5.0",
         "new_bundled":"6.1",
         "partial_version":false
      }
   ],
   "translations":[
      
   ]
}
```

**Comment by jeffpaul** [comment]
@marekdedic does that seem to provide you with parseable data to add this feature for folks who want to trigger checks at RC instead of post-release?

**Comment by marekdedic** [comment]
I think that it does, maybe in combination with the currently used endpoint...
