### ISSUE TITLE
v1.4.0 unable to find readme files

### ISSUE THREAD

**Issue by jeffpaul** [skaut/wordpress-version-checker#962]
I've got two plugins I've started to update:
1. https://github.com/10up/Ad-Refresh-Control/pull/118
2. https://github.com/10up/ads-txt/pull/145

However, when checking the runs on each I'm getting the same error:
`Error: Couldn't get the repository readme. Error message: No "Tested up to:" line found`:
1. https://github.com/10up/Ad-Refresh-Control/actions/runs/5394647326/jobs/9796106790?pr=118
2. https://github.com/10up/ads-txt/actions/runs/5394689367/jobs/9796202669?pr=145

The first one I thought perhaps it might be an issue with the capital letters in the repo name, but the second repo had the same problem.  Curious if there's anything that looks amiss in the workflow file update or the new config JSON that might be causing this?

**Comment by marekdedic** [comment]
Thanks for the report, try 1.4.1 :)

**Comment by jeffpaul** [comment]
Yep, looks good now, thanks!
