### ISSUE TITLE
Unable to detect `readme.txt` file

### ISSUE THREAD

**Issue by jeffpaul** [skaut/wordpress-version-checker#997]
For some reason some of our repos are failing on this action with the following error message:
```
Couldn't get the repository readme. Error message: No "Tested up to:" line found
```

See:
* https://github.com/10up/classifai/actions/runs/5761780285
* https://github.com/10up/simple-local-avatars/actions/runs/5762018240
* https://github.com/10up/simple-local-avatars/actions/runs/5762018240
* https://github.com/10up/simple-page-ordering/actions/runs/5762032315

Meanwhile, other similar repos with the same setup are passing, see:
* https://github.com/10up/ads-txt/actions/runs/5709103723

Any idea if there's something amiss with these four repos above or perhaps just a hiccup in the GitHub Action runs?

**Comment by marekdedic** [comment]
Hmm, that's not to do with GH actions, this is an issue with this package...

I see you're using the `master` version of this action (IMHO not a good idea...), could you please try with 1.4.2 - I can't immediately tell what the issue is here, so maybe some dependency update caused this?

Thanks!

**Comment by dkotter** [comment]
I've switched this from `master` to `v1.5.0` on ClassifAI but still getting the same error: https://github.com/10up/classifai/actions/runs/5826342424/job/15800085376

**Comment by dkotter** [comment]
For what it's worth, I thought it may have to do with line endings, as I'm seeing some of our plugins using LF and some using CRLF for line endings in the `readme.txt` files and seems like the ones that are failing are using CRLF endings. But I did test that in ClassifAI (see https://github.com/10up/classifai/pull/556/commits/96c57eff34445b211e7e137b1aad47f7db486b18) and it still had the same issue

**Comment by jeffpaul** [comment]
@marekdedic I had tried using `@v1` but that didn't work thus I went with `@master` as I didn't want to have to continually bump as you release updates on the v1 branch

**Comment by marekdedic** [comment]
Aha, line endings might be it - I copied the file contents when trying it, didn't download it outright...
